### ISSUE TITLE
Missing bundles

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/orbisserver#87]
Can't start orbisserver there is missing bundles

is looking for org.h2gis.functions.factory package

maybe its because org.h2gis.functions is a fragment bundle ?

```
[ERROR]  o.o.c.c.a.BundleDeployer {main} - Error during the starting of org.orbisgis.orbiswps.service 
org.osgi.framework.BundleException: Unable to resolve org.orbisgis.orbiswps.service [54](R 54.0): missing requirement [org.orbisgis.orbiswps.service [54](R 54.0)] osgi.wiring.package; (&(osgi.wiring.package=org.h2gis.functions.io.geojson)(version>=1.5.0)(!(version>=2.0.0))) Unresolved requirements: [[org.orbisgis.orbiswps.service [54](R 54.0)] osgi.wiring.package; (&(osgi.wiring.package=org.h2gis.functions.io.geojson)(version>=1.5.0)(!(version>=2.0.0)))]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2117) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998) ~[org.apache.felix.framework-5.4.0.jar:na]
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984) ~[org.apache.felix.framework-5.4.0.jar:na]
        at org.ow2.chameleon.core.activators.BundleDeployer.open(BundleDeployer.java:213) [chameleon-core-1.10.9.jar:na]
        at org.ow2.chameleon.core.activators.DirectoryMonitor.addingService(DirectoryMonitor.java:238) [chameleon-core-1.10.9.jar:na]
        at org.ow2.chameleon.core.activators.DirectoryMonitor.addingService(DirectoryMonitor.java:52) [chameleon-core-1.10.9.jar:na]
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941) [org.apache.felix.framework-5.4.0.jar:na]
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870) [org.apache.felix.framework-5.4.0.jar:na]
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) [org.apache.felix.framework-5.4.0.jar:na]
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) [org.apache.felix.framework-5.4.0.jar:na]
        at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901) [org.apache.felix.framework-5.4.0.jar:na]
        at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:991) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:839) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:546) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4557) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.Felix.registerService(Felix.java:3549) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:348) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:355) [chameleon-core-1.10.9.jar:na]
        at org.ow2.chameleon.core.activators.BundleDeployer.start(BundleDeployer.java:86) [chameleon-core-1.10.9.jar:na]
        at org.ow2.chameleon.core.utils.FrameworkManager.start(FrameworkManager.java:117) [chameleon-core-1.10.9.jar:na]
        at org.ow2.chameleon.core.Chameleon.start(Chameleon.java:258) [chameleon-core-1.10.9.jar:na]
        at org.ow2.chameleon.core.Main.main(Main.java:71) [chameleon-core-1.10.9.jar:na]
[ERROR]  o.o.c.c.a.BundleDeployer {main} - Error during the starting of org.orbisgis.orbisserver.baseserver 
org.osgi.framework.BundleException: Unable to resolve org.orbisgis.orbisserver.baseserver [55](R 55.0): missing requirement [org.orbisgis.orbisserver.baseserver [55](R 55.0)] osgi.wiring.package; (&(osgi.wiring.package=org.h2gis.functions.factory)(version>=1.3.0)(!(version>=2.0.0))) [caused by: Unable to resolve org.orbisgis.h2gis-functions [76](R 76.0): missing requirement [org.orbisgis.h2gis-functions [76](R 76.0)] osgi.wiring.package; (osgi.wiring.package=com.vividsolutions.jts.algorithm)] Unresolved requirements: [[org.orbisgis.orbisserver.baseserver [55](R 55.0)] osgi.wiring.package; (&(osgi.wiring.package=org.h2gis.functions.factory)(version>=1.3.0)(!(version>=2.0.0)))]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2117) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998) ~[org.apache.felix.framework-5.4.0.jar:na]
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984) ~[org.apache.felix.framework-5.4.0.jar:na]
        at org.ow2.chameleon.core.activators.BundleDeployer.open(BundleDeployer.java:213) [chameleon-core-1.10.9.jar:na]
        at org.ow2.chameleon.core.activators.DirectoryMonitor.addingService(DirectoryMonitor.java:238) [chameleon-core-1.10.9.jar:na]
        at org.ow2.chameleon.core.activators.DirectoryMonitor.addingService(DirectoryMonitor.java:52) [chameleon-core-1.10.9.jar:na]
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941) [org.apache.felix.framework-5.4.0.jar:na]
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870) [org.apache.felix.framework-5.4.0.jar:na]
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) [org.apache.felix.framework-5.4.0.jar:na]
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) [org.apache.felix.framework-5.4.0.jar:na]
        at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901) [org.apache.felix.framework-5.4.0.jar:na]
        at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:991) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:839) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:546) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4557) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.Felix.registerService(Felix.java:3549) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:348) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:355) [chameleon-core-1.10.9.jar:na]
        at org.ow2.chameleon.core.activators.BundleDeployer.start(BundleDeployer.java:86) [chameleon-core-1.10.9.jar:na]
        at org.ow2.chameleon.core.utils.FrameworkManager.start(FrameworkManager.java:117) [chameleon-core-1.10.9.jar:na]
        at org.ow2.chameleon.core.Chameleon.start(Chameleon.java:258) [chameleon-core-1.10.9.jar:na]
        at org.ow2.chameleon.core.Main.main(Main.java:71) [chameleon-core-1.10.9.jar:na]
[ERROR]  o.o.c.c.a.BundleDeployer {main} - Error during the starting of org.orbisgis.orbisserver.wpsservice 
org.osgi.framework.BundleException: Unable to resolve org.orbisgis.orbisserver.wpsservice [65](R 65.0): missing requirement [org.orbisgis.orbisserver.wpsservice [65](R 65.0)] osgi.wiring.package; (&(osgi.wiring.package=org.orbisgis.orbiswps.service.model)(version>=5.1.0)(!(version>=6.0.0))) [caused by: Unable to resolve org.orbisgis.orbiswps.service [54](R 54.0): missing requirement [org.orbisgis.orbiswps.service [54](R 54.0)] osgi.wiring.package; (&(osgi.wiring.package=org.h2gis.functions.io.geojson)(version>=1.5.0)(!(version>=2.0.0)))] Unresolved requirements: [[org.orbisgis.orbisserver.wpsservice [65](R 65.0)] osgi.wiring.package; (&(osgi.wiring.package=org.orbisgis.orbiswps.service.model)(version>=5.1.0)(!(version>=6.0.0)))]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2117) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998) ~[org.apache.felix.framework-5.4.0.jar:na]
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984) ~[org.apache.felix.framework-5.4.0.jar:na]
        at org.ow2.chameleon.core.activators.BundleDeployer.open(BundleDeployer.java:213) [chameleon-core-1.10.9.jar:na]
        at org.ow2.chameleon.core.activators.DirectoryMonitor.addingService(DirectoryMonitor.java:238) [chameleon-core-1.10.9.jar:na]
        at org.ow2.chameleon.core.activators.DirectoryMonitor.addingService(DirectoryMonitor.java:52) [chameleon-core-1.10.9.jar:na]
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941) [org.apache.felix.framework-5.4.0.jar:na]
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870) [org.apache.felix.framework-5.4.0.jar:na]
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) [org.apache.felix.framework-5.4.0.jar:na]
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) [org.apache.felix.framework-5.4.0.jar:na]
        at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901) [org.apache.felix.framework-5.4.0.jar:na]
        at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:991) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:839) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:546) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4557) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.Felix.registerService(Felix.java:3549) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:348) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:355) [chameleon-core-1.10.9.jar:na]
        at org.ow2.chameleon.core.activators.BundleDeployer.start(BundleDeployer.java:86) [chameleon-core-1.10.9.jar:na]
        at org.ow2.chameleon.core.utils.FrameworkManager.start(FrameworkManager.java:117) [chameleon-core-1.10.9.jar:na]
        at org.ow2.chameleon.core.Chameleon.start(Chameleon.java:258) [chameleon-core-1.10.9.jar:na]
        at org.ow2.chameleon.core.Main.main(Main.java:71) [chameleon-core-1.10.9.jar:na]
[ERROR]  o.o.c.c.a.BundleDeployer {main} - Error during the starting of org.orbisgis.h2gis-utilities 
org.osgi.framework.BundleException: Unable to resolve org.orbisgis.h2gis-utilities [67](R 67.0): missing requirement [org.orbisgis.h2gis-utilities [67](R 67.0)] osgi.wiring.package; (osgi.wiring.package=com.vividsolutions.jts.algorithm) Unresolved requirements: [[org.orbisgis.h2gis-utilities [67](R 67.0)] osgi.wiring.package; (osgi.wiring.package=com.vividsolutions.jts.algorithm)]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2117) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998) ~[org.apache.felix.framework-5.4.0.jar:na]
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984) ~[org.apache.felix.framework-5.4.0.jar:na]
        at org.ow2.chameleon.core.activators.BundleDeployer.open(BundleDeployer.java:213) [chameleon-core-1.10.9.jar:na]
        at org.ow2.chameleon.core.activators.DirectoryMonitor.addingService(DirectoryMonitor.java:238) [chameleon-core-1.10.9.jar:na]
        at org.ow2.chameleon.core.activators.DirectoryMonitor.addingService(DirectoryMonitor.java:52) [chameleon-core-1.10.9.jar:na]
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941) [org.apache.felix.framework-5.4.0.jar:na]
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870) [org.apache.felix.framework-5.4.0.jar:na]
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) [org.apache.felix.framework-5.4.0.jar:na]
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) [org.apache.felix.framework-5.4.0.jar:na]
        at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901) [org.apache.felix.framework-5.4.0.jar:na]
        at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:991) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:839) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:546) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4557) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.Felix.registerService(Felix.java:3549) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:348) [chameleon-core-1.10.9.jar:na]
        at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:355) [chameleon-core-1.10.9.jar:na]
        at org.ow2.chameleon.core.activators.BundleDeployer.start(BundleDeployer.java:86) [chameleon-core-1.10.9.jar:na]
        at org.ow2.chameleon.core.utils.FrameworkManager.start(FrameworkManager.java:117) [chameleon-core-1.10.9.jar:na]
        at org.ow2.chameleon.core.Chameleon.start(Chameleon.java:258) [chameleon-core-1.10.9.jar:na]
        at org.ow2.chameleon.core.Main.main(Main.java:71) [chameleon-core-1.10.9.jar:na]

```

**Comment by nicolas-f** [comment]
@qhesry Same issue ?

**Comment by qhesry** [comment]
Yes, I got the same issue.

**Comment by nicolas-f** [comment]
@qhesry please read your emails
